[package]
name = "usbfs"
version = "0.1.0"
authors = ["Daniel Goertzen <daniel.goertzen@gmail.com>"]

[features]
default = []

[dependencies]
libc = "0.2"
nix = "0.13"
bitflags = "1.0"
mio = { version = "0.6", optional = true }

