[package]
name = "usbfs"
version = "0.1.3"
authors = ["Daniel Goertzen <daniel.goertzen@gmail.com>"]
edition = "2021"

[features]
default = []

[dependencies]
libc = "0.2"
nix = "0.24"
bitflags = "1.3"
mio = { version = "0.8", optional = true }
